# Generated by Django 3.2 on 2022-12-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_position_passport_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
