# Generated by Django 3.2 on 2022-12-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_vipclient_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipclient',
            name='donation_amount',
            field=models.IntegerField(),
        ),
    ]
