# Generated by Django 3.2 on 2022-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_vipclient_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipclient',
            name='vip_status_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
